settings:
  migration: 'laravel'
  db-execute: 'schema'
  db:
    driver: 'pdo_pgsql'
    host: 'localhost'
    dbname: 'postgres'
    port: 5433
    user: 'postgres'
    password: 'secret'
args:
  file: ''
  tab: ''
  project: ''
  dir: ''
  filename: ''